clear all;
clc

HF0 = figure('Units','characters', ...
	'Color',[0.325 0.314 0.5], ...
	'FileName','d:\tank\form.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[30 5 152 42], ...
	'Tag','Figure1', ...
	'ToolBar','auto');
%*************Edit********************
HF1 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
    'Callback','sdop_calc',...
	'BackgroundColor',[1 1 1], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[12 8 8 1.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','Base_Radius');
HF2 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
    'Callback','sdop_calc',...
	'BackgroundColor',[1 1 1], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[12 4 8 1.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','Hole_Radius');

%****************Text Box************************
HF5 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
	'BackgroundColor',[0.325 0.314 0.5], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[4 8 6 1.25], ...
	'String','pol = ', ...
	'Style','text', ...
	'Tag','text1');
HF6 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
	'BackgroundColor',[0.325 0.314 0.5], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[4 4 6 1.25], ...
	'String','dens= ', ...
	'Style','text', ...
	'Tag','text2');

%****************Sliders********************
HF9 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
    'Callback','sdop_calc2',...
	'BackgroundColor',[.9 .9 .9], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[4 6 20 1.5], ...
	'Style','slider', ...
    'Max',100,...
    'Min',0,...
    'Value',0,...
	'Tag','Base_Radius_Slider');
HF10 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
    'Callback','sdop_calc2',...
	'BackgroundColor',[.9 .9 .9], ...
	'FontSize',8, ...
	'ListboxTop',1.0, ...
	'Position',[4 2 20 1.5], ...
	'Style','slider', ...
    'Max',1000,...
    'Min',0,...
    'Value',0,...
	'Tag','Hole_Radius_Slider');

%*****************push buttons*******************************
HF12 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
	'BackgroundColor',[.925 .914 .847], ...
	'Callback','sdop_plot', ...
	'FontSize',8, ...
	'ListboxTop',0, ...
	'Position',[4 10 14 2], ...
	'String','Plot', ...
	'Tag','Plot');
HF13 = uicontrol('Parent',HF0, ...
	'Units','characters', ...
	'BackgroundColor',[.925 .914 .847], ...
	'Callback','sdop_helpmsg', ...
	'FontSize',8, ...
	'ListboxTop',0, ...
	'Position',[4 0 10 1.5], ...
	'String','Help', ...
	'Tag','Help');
