# Use a persistent compiler cache to speed up rebuilds for a single job.
#.use-ccache:
#  cache:
#    key: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
#    paths:
#      - ccache/

.use-cuda:
  variables:
    ENV_COMPILER: "NVCCFLAGS=" #\"-arch sm_52\""
    CUDA_OPTIONS: "--with-cuda"

.use-mpi:
  variables:
    ENV_COMPILER: "CC=mpicc CXX=mpiCC"
    MPI_OPTIONS: "--enable-mpi"

.use-openmp:
  variables:
    OPENMP_OPTIONS: "--enable-openmp"

.use-clang:
  variables:
    ENV_COMPILER: "CC=clang CXX=clang++ CFLAGS=-fopenmp=libomp CXXFLAGS=-fopenmp=libomp"

.use-share:
  variables:
    ENV_SHARE: "--disable-static --enable-shared"

.use-debug:
  variables:
    ENV_DEBUG: "--enable-debug"

  #before_script:
  #  - mkdir -p ccache
  #  - export CCACHE_BASEDIR=${PWD}
  #  - export CCACHE_DIR=${PWD}/ccache
  

.gromos:base:configure:
  stage: configure-build
  script:
    - echo $ENV_COMPILER
    - echo $OPENMP_OPTIONS
    - echo $MPI_OPTIONS
    - echo $CUDA_OPTIONS
    - echo $ENV_SHARE
    - echo $ENV_DEBUG
    - echo $BUILD_DIR
    - cd md++/
    - ./Config.sh $ENV_COMPILER
    - cd ..
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - ../md++/configure $ENV_SHARE $OPENMP_OPTIONS $MPI_OPTIONS $CUDA_OPTIONS $ENV_COMPILER $ENV_DEBUG
  artifacts:
    when: always
    paths:
      - md++
      - $BUILD_DIR

.gromos:base:configure_cmake:
  stage: configure-build
  script:
    - echo "$ENV_COMPILER"
    - cmake --version
    - >
      cmake -S md++ -B "$BUILD_DIR"
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE:-Release}
      -DUSE_CUDA=${USE_CUDA:-OFF}
      -DOMP=${USE_OPENMP:-OFF}
      -DMPI=${USE_MPI:-OFF}
      -DBUILD_SHARED_LIBS=${USE_SHARE:-OFF}
  artifacts:
    when: always
    paths:
      - md++
      - $BUILD_DIR

.gromos:base:build:
  stage: build
  script:
    - echo $ENV_COMPILER
    - echo $OPENMP_OPTIONS
    - echo $MPI_OPTIONS
    - echo $CUDA_OPTIONS
    - echo $ENV_SHARE
    - echo $ENV_DEBUG
    - echo $BUILD_DIR
    - echo $BIN_PATH
    - cd $BUILD_DIR
    - make -j4 $ENV_COMPILER
    - make install $ENV_COMPILER
  artifacts:
    when: always
    paths:
      - $BUILD_DIR/lib
      - $BIN_PATH

.gromos:base:build_make_check:
  stage: build_make_check
  script: 
    - echo $ENV_COMPILER
    - echo $OPENMP_OPTIONS
    - echo $MPI_OPTIONS
    - echo $CUDA_OPTIONS
    - echo $ENV_SHARE
    - echo $ENV_DEBUG
    - echo $BUILD_DIR
    - echo $BIN_PATH
    - cd $BUILD_DIR
    - make -j4 $ENV_COMPILER
    - make check $ENV_COMPILER
    - make install $ENV_COMPILER
  artifacts:
    when: always
    paths:
      - $BUILD_DIR/lib
      - $BUILD_DIR/src/check/test-suite.log
      - $BIN_PATH

.gromos:base:build_make_test_cmake:
  stage: build_make_check
  script: 
    - echo $BUILD_DIR
    - echo $BIN_PATH
    - cmake --build $BUILD_DIR -j 8
    - cd $BUILD_DIR
    - make test
    - cd ..
    - cmake --install $BUILD_DIR
  artifacts:
    when: always
    paths:
      - $BUILD_DIR/Testing
      - $BUILD_DIR/install_manifest.txt
      - $BIN_PATH

# This tests contains short tests (e.g. the tutorial peptide)
# The corresponding tests are in md++/contrib/py_gr_utils/tests_short/ . Note that there is a mismatch in the name. The tests for sim_test are in tests_short.
.gromos:base:sim_test:
  stage: sim_test
  script: 
    - echo $CI_PROJECT_DIR
    - echo $BIN_PATH
    - echo $TEST_REPO
    - echo $PRE_MD_BIN
    - echo $OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
    - echo $OMPI_ALLOW_RUN_AS_ROOT
    - git clone https://gromosx.boku.ac.at/gromos_tests/gromos_test_files.git
    - cd md++/contrib/py_gr_utils/tests_short/
    - pytest-3 --junitxml=${CI_PROJECT_DIR}/sim_test_report.xml
  artifacts:
    when: always
    paths:
      - $BUILD_DIR
    reports:
      junit:
        - sim_test_report.xml

# This is set contains more extensive tests that are only to be run on request (e.g. AEDS tests).
# This set of tests will only be run when the commit message contains the string "-fullTest", otherwise they are set to manual. Manual tests can be triggered manually in gitlab web.
# When adding test sets here it is also important to add the corresponding entries in the files in gromos.matrix.
# The actual tests are typically performed by pytest-3. If it is called as part of the testing pipeline, do not forget to place the corresponding tests in the correct directory (e.g. md++/contrib/py_gr_utils/tests_extensive/ for the test set "tests_extensive")
.gromos:base:sim_test_extensive:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-fullTest/
      when: always
    - when: manual
  stage: sim_test_extensive
  script: 
    - echo $CI_PROJECT_DIR
    - echo $BIN_PATH
    - echo $TEST_REPO
    - echo $PRE_MD_BIN
    - echo $OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
    - echo $OMPI_ALLOW_RUN_AS_ROOT
    - git clone https://gromosx.boku.ac.at/gromos_tests/gromos_test_files.git
    - cd md++/contrib/py_gr_utils/tests_extensive/
    - pytest-3 --junitxml=${CI_PROJECT_DIR}/sim_test_report.xml
  artifacts:
    when: always
    paths:
      - $BUILD_DIR
    reports:
      junit:
        - sim_test_extensive_report.xml

include:
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-cmake.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-cmake_debug.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-cmake-openmp.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-cmake-mpi.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cmake-cuda-11.6.1.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cmake-openmp-cuda-11.6.1.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cmake-cuda-11.6.1_debug.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cmake-cuda-11.6.1_shared.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-llvm.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-22.04-mpi.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-llvm.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-mpi.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-mpi_debug.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cuda-11.6.1.yml'
  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-20.04-cuda-11.6.1_debug.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-18.04.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-18.04-llvm.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-18.04-mpi.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-16.04.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-16.04-llvm.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-16.04-mpi.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/ubuntu-16.04-cuda-10.2.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-11.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-11-mpi.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-10.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-10-mpi.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-9.yml'
#  - local: 'md++/admin/gitlab-ci/gromos.matrix/debian-9-mpi.yml'
