gromos:ubuntu-20.04-cuda-11.6.1-debug:configure:
  extends:
    - .gromos:base:configure
    - .use-openmp
    - .use-cuda
    - .use-share
    - .use-debug
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-cuda-11.6.1
  variables:
    BUILD_DIR: build_debug

gromos:ubuntu-20.04-cuda-11.6.1-debug:build:
  extends:
    - .gromos:base:build
    - .use-openmp
    - .use-cuda
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-cuda-11.6.1
  variables:
    BUILD_DIR: build_debug
    BIN_PATH: ${BUILD_DIR}/bin/md
  needs:
    - job: gromos:ubuntu-20.04-cuda-11.6.1-debug:configure
