gromos:ubuntu-20.04-mpi:configure:
  extends:
    - .gromos:base:configure
    - .use-mpi
    - .use-share
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-mpi
  variables:
    BUILD_DIR: build

gromos:ubuntu-20.04-mpi:build_make_check:
  extends:
    - .gromos:base:build_make_check
    - .use-mpi
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-mpi
  variables:
    BUILD_DIR: build
    BIN_PATH: ${BUILD_DIR}/bin/md_mpi
  needs:
    - job: gromos:ubuntu-20.04-mpi:configure

gromos:ubuntu-20.04-mpi:sim_test:
  extends:
    - .gromos:base:sim_test
    - .use-mpi
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-mpi
  variables:
    BUILD_DIR: build
    BIN_PATH: ${BUILD_DIR}/bin/md_mpi
    TEST_REPO: $CI_PROJECT_DIR/gromos_test_files/
    PRE_MD_BIN: "mpirun -np 4"
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    OMPI_ALLOW_RUN_AS_ROOT: 1
  needs:
    - job: gromos:ubuntu-20.04-mpi:build_make_check


gromos:ubuntu-20.04-mpi:sim_test_extensive:
  extends:
    - .gromos:base:sim_test_extensive
    - .use-mpi
  image: ${CI_REGISTRY}/gromos/gromosxx/gromos-ubuntu-20.04-mpi
  variables:
    BUILD_DIR: build
    BIN_PATH: ${BUILD_DIR}/bin/md_mpi
    TEST_REPO: $CI_PROJECT_DIR/gromos_test_files/
    PRE_MD_BIN: "mpirun -np 4"
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    OMPI_ALLOW_RUN_AS_ROOT: 1
  needs:
    - job: gromos:ubuntu-20.04-mpi:build_make_check
